idx_bt2: /fs/project/PES0738/maxATAC_inputs/genome_inf/hg38/bowtie2_index/hg38
macs_g: hs
hg38_fasta: /data/miraldiLab/databank/genome_inf/hg38/Homo_sapiens.GRCh38.fa
keepChr: 'chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22'
blacklist: '/fs/project/PES0738/maxATAC_inputs/genome_inf/hg38_maxatac_blacklist.bed'
output_dir: /fs/project/PES0738/workflows/chip/outputs
input_dir: /fs/project/PES0738/testing/chip_snakemake/fastq
meta_file: /fs/project/PES0738/workflows/chip/inputs/maxATAC_v1_sample_chip_meta.tsv
meme_motif_file: /fs/project/PES0738/workflows/chip/inputs/human_cisbp200.motif