idx_bt2: /fs/ess/project/PES0738/maxATAC_inputs/genome_inf/hg38/bowtie2_index/hg38
macs_g: hs
hg38_fasta: /fs/ess/PES0738/maxATAC_inputs/genome_inf/hg38/Homo_sapiens.GRCh38.fa
keepChr: 'chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22'
blacklist: '/fs/ess/PES0738/maxATAC_inputs/genome_inf/hg38/hg38_maxatac_blacklist_published.bed'
output_dir: /fs/ess/project/PES0738/20220614_maxatac_v1_data/snakemake/chip/outputs
input_dir: /fs/ess/project/PES0738/20220614_maxatac_v1_data/snakemake/chip/outputs
meta_file: /fs/ess/PES0738/20220614_maxatac_v1_data/snakemake/chip/inputs/chip_meta.tsv
meme_motif_file: /fs/ess/PES0738/20220614_maxatac_v1_data/snakemake/chip/inputs/human_cisbp200.motif