idx_bt2: ./bowtie2_index/hg38
macs_g: hs
hg38_fasta: ./Homo_sapiens.GRCh38.fa
keepChr: 'chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22'
blacklist: './hg38_blacklist.bed'
output_dir: ./outputs
input_dir: ./fastq
meta_file: ./chip_meta.tsv
meme_motif_file: ./inputs/human_cisbp200.motif